### ISSUE TITLE
Build fails as dependencies are not in maven reposirory

### ISSUE THREAD

**Issue by retog** [RMLio/RML-Processor#10]
The following artifacts could not be resolved: be.ugent.mmlab.rml:RML-ConditionsHandler:jar:1.0, be.ugent.mmlab.rml:RML-MapDocHandler:jar:1.0, be.ugent.mmlab.rml:RML-LogicalSourceHandler:jar:1.0, be.ugent.mmlab.rml:RML-DataRetrievalHandler:jar:1.0, be.ugent.mmlab.rml:RML-MetadataHandler:jar:1.0: Could not find artifact be.ugent.mmlab.rml:RML-ConditionsHandler:jar:1.0

**Comment by pelzerim** [comment]
Try to clone this instead: https://github.com/RMLio/RML-Mapper
(see closed issue https://github.com/RMLio/RML-Processor/issues/6 )

**Comment by sztamas** [comment]
I think it would be very helpful if you've added that note to the README file.
 
Otherwise, people will keep hitting the same problem, like I just did for example.

Thanks

**Comment by bjdmeest** [comment]
Updated at 1447f12

**Comment by retog** [comment]
@pelzerim having to build a reactor build makes sense when the dependencies are SNAPSHOT dependencies, but here the dependecies are relased dependecies according to their version identifier, so tthey should also be avaliable in the maven repository. That seems to be the whole point of having SNAPSHOT and non-SNAPSHOT dependencies.

**Comment by sztamas** [comment]
Thanks @bjdmeest
