### ISSUE TITLE
grel:isSet no longer exists

### ISSUE THREAD

**Issue by adlerfaulkner** [RMLio/RML-Processor#20]
Was looking through the tests folder for examples of mappings with grel functions. 

[mapping_isSet.rml.ttl](https://github.com/RMLio/RML-Processor/blob/master/src/test/resources/exampleFN/mapping_isSet.rml.ttl) uses a long gone grel function `isSet`. Was removed here https://github.com/FnOio/grel-functions-fno/commit/738c5b380841f764fe13af58253dc1b9ec90e44e in 2017.

**Comment by bjdmeest** [comment]
This repository is no longer maintained, please have a look at https://github.com/RMLio/rmlmapper-java, which is actively maintained. Currently supported functions can be found at https://rml.io/docs/rmlmapper/default-functions/
