### ISSUE TITLE
XML iterator seems to ignore tag with "xmlns"

### ISSUE THREAD

**Issue by alemela** [RMLio/RML-Processor#4]
For example for: `<project xmlns="http://example.org">` the iterator pointing to `project` leads to nothing.

**Comment by andimou** [comment]
If the default namespace for XML is overwritten, XPath has no way to refer to it, thus an XPath processor requires to be informed regarding this namespace.

In the case of the RML Processor, you may hard code the prefix default namespace.
To be more precise, you may add a custom namespace by updating both of the following two files:

add a custom namespace after line 52 of https://github.com/RMLio/RML-LogicalSourceHandler/blob/master/src/main/java/be/ugent/mmlab/rml/logicalsourcehandler/termmap/concrete/XPathTermMapProcessor.java#L52.

add the same custom namespace and after line 75 of https://github.com/RMLio/RML-Processor/blob/development/src/main/java/be/ugent/mmlab/rml/processor/concrete/XPathProcessor.java#L75
