### ISSUE TITLE
dependency problem with RML-ConditionsHandler:jar:1.0

### ISSUE THREAD

**Issue by seralf** [RMLio/RML-Processor#6]
Hi I'm trying to test the library, but after `git clone` and `mvn clean install` I had the following error:

```
...
[ERROR] Failed to execute goal on project RML-Processor: Could not resolve dependencies for project be.ugent.mmlab.rml:RML-Processor:jar:0.2: The following artifacts could not be resolved: be.ugent.mmlab.rml:RML-ConditionsHandler:jar:1.0, be.ugent.mmlab.rml:RML-MapDocHandler:jar:1.0, be.ugent.mmlab.rml:RML-DataRetrievalHandler:jar:1.0, be.ugent.mmlab.rml:RML-MetadataHandler:jar:1.0: Could not find artifact be.ugent.mmlab.rml:RML-ConditionsHandler:jar:1.0 in repository.jboss.org (https://repository.jboss.org/nexus/content/repositories/thirdparty-releases) -> [Help 1]
...
```

Trying to re-compile manually the module, I've found that it is currently on version 1.1-SNAPSHOT: I've tried to update the dependency with no luck then.

**Comment by andimou** [comment]
Did you clone the RML-Processor or the RML-Mapper? If RML-Processor, which branch? 

I'd suggest that you start with the [RML-Mapper](https://github.com/RMLio/RML-Mapper.git). Let me know if that worked out.

**Comment by seralf** [comment]
Hi thank you very much for the explanation: I was trying with the processor
repo , master branch, trying again instead with the RML-Mapper repo it now
correctly compiles! :-)

2016-07-16 14:00 GMT+02:00 andimou notifications@github.com:
