### ISSUE TITLE
Allow specification of default namespace

### ISSUE THREAD

**Issue by zacharywhitley** [RMLio/RML-Processor#8]
This might be more applicable to the specification but I'll suggest it here. Allow the specification of the default xml namespace for xpath expressions used in referenceFormulation ql:XPath

**Comment by andimou** [comment]
I am not sure if this is a good idea actually.. 

The problem I see is that it is only a matter of XPath, that being said a particular reference formulation.
Perhaps it makes some sense to have a custom reference formulation, e.g. `ql:XPathCustom`, which has a description and its description has a field that describes the XML namespaces, eg. `ql:XPathCustom` ex:namespace `<http://example.com/namespace>` and specify that this is of type `ql:XPath`, e.g. `ql:XPathCustom rdfs:subClassOf ql:XPath`. In this case, the RML Processor should know that there might be such descriptions. 

But still, that would mean working with some custom vocabulary and RML tries to keep working with W3C recommended vocabularies and, to the best of my knowledge, there is no vocabulary that describes XML files and I am not even sure if it makes sense to describe custom XPath descriptions after all.

Even though a bit frustrating, what I usually do is to add the namespaces in the source code if I want to use them, as it occurs at `https://github.com/RMLio/RML-LogicalSourceHandler/blob/master/src/main/java/be/ugent/mmlab/rml/logicalsourcehandler/termmap/concrete/XPathTermMapProcessor.java#L52`

**Comment by zacharywhitley** [comment]
Perhaps a command line option on the processor?
